# Generated by Django 4.2.3 on 2023-09-23 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, null=True)),
                ("password", models.CharField(max_length=50, null=True)),
                ("role", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=50, null=True)),
                ("splace", models.CharField(max_length=50, null=True)),
                ("sphone", models.CharField(max_length=50, null=True)),
                ("password", models.CharField(max_length=50, null=True)),
                ("username", models.CharField(max_length=50, null=True)),
                ("sellerstatus", models.CharField(max_length=50, null=True)),
                (
                    "login",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lgrgvwapp.log"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(max_length=30, null=True, upload_to="")),
                ("name", models.CharField(max_length=30, null=True)),
                ("descriptiion", models.CharField(max_length=120, null=True)),
                ("price", models.CharField(max_length=30, null=True)),
                ("ownership", models.CharField(max_length=30, null=True)),
                ("paper", models.CharField(max_length=30, null=True)),
                (
                    "sellerid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lgrgvwapp.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bname", models.CharField(max_length=50, null=True)),
                ("bplace", models.CharField(max_length=50, null=True)),
                ("bphone", models.CharField(max_length=50, null=True)),
                ("password", models.CharField(max_length=50, null=True)),
                ("username", models.CharField(max_length=50, null=True)),
                ("buyerstatus", models.CharField(max_length=50, null=True)),
                (
                    "login",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lgrgvwapp.log"
                    ),
                ),
            ],
        ),
    ]
