# Generated by Django 4.2.3 on 2023-10-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lgrgvwapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="sellerid",
            new_name="seller_id",
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
