# Generated by Django 4.2.3 on 2023-10-11 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lgrgvwapp", "0002_rename_sellerid_car_seller_id_alter_car_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sellerid", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=30, null=True)),
                ("descriptiion", models.CharField(max_length=30, null=True)),
                ("price", models.CharField(max_length=30, null=True)),
                ("ownership", models.CharField(max_length=30, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("paper", models.CharField(max_length=120, null=True)),
                (
                    "carid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lgrgvwapp.car"
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lgrgvwapp.buyer",
                    ),
                ),
            ],
        ),
    ]
