# Generated by Django 4.2.3 on 2023-10-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lgrgvwapp", "0003_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="userid",
            new_name="buyerid",
        ),
        migrations.AddField(
            model_name="booking",
            name="bookingdate",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="bookingstatus",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="buyername",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="quantity",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="sellername",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="sellerid",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="lgrgvwapp.seller",
            ),
        ),
    ]
