# Generated by Django 4.2.3 on 2023-10-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lgrgvwapp",
            "0004_rename_userid_booking_buyerid_booking_bookingdate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="quantity",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
