# Generated by Django 4.2.3 on 2023-10-30 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lgrgvwapp", "0005_car_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="quantity",
        ),
    ]
